FROM govpf/alpine:3

LABEL govpf.fromimage="govpf/alpine:3"
LABEL govpf.category="utility"

RUN apk add -u \
            bash \
            bind-tools \
            curl \
            iperf \
            netcat-openbsd \
            nmap \
            python3 \
            socat \
            tcpdump \
            tcptraceroute \
            vim \
            wget

