FROM govpf/alpine:3

RUN apk add -u \
            bash \
            bind-tools \
            curl \
            iperf \
            netcat-openbsd \
            nmap \
            python3 \
            socat \
            tcpdump \
            tcptraceroute \
            vim \
            wget

