FROM govpf/debian:buster

RUN apt update && apt install -y \
                        bash \
                        curl \
                        dnsutils \
                        netcat \
                        nmap \
                        python3 \
                        socat \
                        tcpdump \
                        vim \
                        wget
